name: student_management_web
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'  # Adjust according to your Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.0  # Use a stable version of hive
  hive_flutter: ^1.1.0  # Use the corresponding version of hive_flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0  # Match this with hive version
  build_runner: ^2.1.10
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true